import Head from 'next/head'
import Header from '../components/Header'
import { getSession } from 'next-auth/react'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';
import { db } from '../firebase';
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home({ session, posts }) {
  if(!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Facebook Clone | Brown Surfing</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:image" content="/images/facebook.jpg"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header />
      <main className='flex bg-gray-100'>
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed posts={posts} />
        {/* Widgets */}
        <Widgets />

      </main>
    </div>
  )
}

export async function getServerSideProps(context){
  // get the user
  const session = await getSession(context);

  const posts = await db.collection("posts").orderBy("timestamp", "desc").get();

  const docs = posts.docs.map(post => ({
    id: post.id,
    ...post.data(),
    timestamp: null
  }))

  return {
    props: {
      session,
      posts: docs,
    }
  }
}